# Generated by Django 3.2.13 on 2022-07-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('event_description', models.TextField()),
                ('event_start_time', models.TimeField()),
                ('event_end_time', models.TimeField()),
                ('event_location', models.CharField(max_length=255)),
                ('event_ticket_link', models.URLField()),
                ('event_ticket_host', models.CharField(max_length=255)),
            ],
        ),
    ]
