# Generated by Django 3.2.13 on 2022-07-25 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_events_event_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'ordering': ('event_date',)},
        ),
    ]
