# Generated by Django 3.2.13 on 2022-07-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BreweryTourBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=22)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('number_of_people', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], verbose_name='Number of people')),
                ('date', models.DateField()),
                ('time', models.CharField(choices=[('11:30', '11:30'), ('11:45', '11:45'), ('12:00', '12:00'), ('12:15', '12:15')], max_length=15)),
                ('phone_number', models.CharField(max_length=20)),
                ('date_booked', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='TaproomBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=22)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('number_of_people', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], verbose_name='Number of people')),
                ('date', models.DateField()),
                ('time', models.CharField(choices=[('12:00', '13:00'), ('12:30', '13,30'), ('13:00', '14:00'), ('13:30', '14,30'), ('14:00', '15:00'), ('14:30', '15:30'), ('15:00', '16:00'), ('15:30', '16,30'), ('16:00', '17:00'), ('16:30', '17,30'), ('17:00', '18:00'), ('17:30', '18:30'), ('18:00', '19:00'), ('18:30', '19,30'), ('19:00', '20:00'), ('19:30', '20:30'), ('20:00', '21:00'), ('20:30', '21:30'), ('21:00', '22:30'), ('21:30', '22:30'), ('22:00', '23:00')], max_length=15)),
                ('phone_number', models.CharField(max_length=20)),
                ('date_booked', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
