# Generated by Django 3.2.13 on 2022-07-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brewerytourbooking',
            name='time',
            field=models.CharField(choices=[('13:00', '14:00'), ('14:30', '15:30')], max_length=15),
        ),
    ]
