# Generated by Django 3.2.13 on 2022-07-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20220724_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brewerytourbooking',
            name='time',
            field=models.CharField(choices=[('13:00', '13:00'), ('14:30', '14:30')], max_length=15),
        ),
    ]
