# Generated by Django 3.2.13 on 2022-06-10 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_stock',
            new_name='color',
        ),
    ]
