# Generated by Django 3.2.13 on 2022-06-11 10:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_product_stock_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='descriptive_words',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=254, null=True), default=list, size=None),
        ),
    ]
